### ISSUE TITLE
Improper handling of package path extraction

### ISSUE THREAD

**Issue by computerquip-streamlabs** [backtrace-labs/backtrace-node#13]
```
App threw an error during load
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at fetchModulePackageJson (D:\projects\streamlabs\streamlabs-obs\node_modules\backtrace-node\lib\index.js:317:24)
    at Object.initialize (D:\projects\streamlabs\streamlabs-obs\node_modules\backtrace-node\lib\index.js:131:21)
    at Object.<anonymous> (D:\projects\streamlabs\streamlabs-obs\main.js:42:13)
    at Object.<anonymous> (D:\projects\streamlabs\streamlabs-obs\main.js:431:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (D:\Projects\streamlabs\streamlabs-obs\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
    at Object.<anonymous> (D:\Projects\streamlabs\streamlabs-obs\node_modules\electron\dist\resources\default_app.asar\main.js:325:5)
    at Object.<anonymous> (D:\Projects\streamlabs\streamlabs-obs\node_modules\electron\dist\resources\default_app.asar\main.js:361:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Using backtrace-node to send callstacks for Electron when uncaught exceptions happen in either the main process or renderer. The error above seems to happen any time I specify `disableGlobalHandler` as an option to `initialize`. I'm disabling the handler since I'd like to provide the user a dialog specifying the application wants to shut down. As a result, I have a custom handler which synchronously sends the report, then spawns the dialog box, then quits the application. If there's a better way of accomplishing this, please let me know.

**Comment by computerquip-streamlabs** [comment]
Here's the offending code: 
```
  backtrace.initialize({
    disableGlobalHandler: true,
    endpoint: "https://streamlabs.sp.backtrace.io:6098",
    token: "e3f92ff3be69381afe2718f94c56da4644567935cc52dec601cf82b3f52a06ce"
  });
```

**Comment by sbahra** [comment]
Thanks the submission! I'll get back to you tomorrow.

**Comment by computerquip-streamlabs** [comment]
This appears to be fixed with this commit: https://github.com/backtrace-labs/backtrace-node/commit/b4207d9a2e3f9e9899b0fac17d82fd6f932ba3cf

Thanks!
