### ISSUE TITLE
Crashes in Windows 10 when running within Electron

### ISSUE THREAD

**Issue by mbreaux** [backtrace-labs/backtrace-node#17]
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at StreamSink.gotAllStdin (C:\Users\mbreaux\Downloads\xxxx\electron-quick-start\node_modules\backtrace-node\lib\async_report.js:17:21)
    at StreamSink.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:641:14)
    at endWritable (_stream_writable.js:649:3)
    at StreamSink.Writable.end (_stream_writable.js:589:5)
    at Readable.onend (_stream_readable.js:634:10)
    at Object.onceWrapper (events.js:273:13)
    at Readable.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1090:12)

[OK]
```

This error occurs when launching a default electron-quick-start app with the following initialization code added to createWindow:

```
bt.initialize({
    endpoint:
      'https://<some_universe>.sp.backtrace.io:6098',
    token: '<some_token>',
    allowMultipleUncaughtExceptionListeners: true,
  });
  bt.report(new Error('Error testing'));
```

The error above appears in a Windows dialog box.  Afterward, the Electron app's GUI freezes and has to be killed in Task Manager.  Neither backtrace-node nor the main process' crashreporter will send an error to Backtrace.

**Comment by mbreaux** [comment]
When passing `debugBacktrace` to `bt.initialize`, the error changes:

```
t>npm start

> electron-quick-start@1.0.0 start C:\Users\mbreaux\Downloads\xxx\electron-quick-start
> electron .


Unable to read /proc/self/status: ENOENT: no such file or directory, open '/proc/self/status'
Unable to exec uname -m: spawn uname ENOENT
Unable to exec uname -r: spawn uname ENOENT
Unable to exec uname -s: spawn uname ENOENT
Unable to exec uname -v: spawn uname ENOENT
Unable to exec uname -v: uname exited with code -4058
Unable to read /proc/self/status: ENOENT: no such file or directory, open '/proc/self/status'


C:\Users\mbreaux\Downloads\improbable\electron-quick-start\node_modules\backtrace-node\lib\index.js:101
    throw err;
    ^

Error: callback called twice
    at onCb (C:\Users\mbreaux\Downloads\xxx\electron-quick-start\node_modules\pend\index.js:36:23)
    at C:\Users\mbreaux\Downloads\xxx\electron-quick-start\node_modules\backtrace-node\lib\send_report.js:326:9
    at ChildProcess.<anonymous> (C:\Users\mbreaux\Downloads\xxx\electron-quick-start\node_modules\backtrace-node\lib\send_report.js:348:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

Those uname and /proc references are going to have to go...

**Comment by sbahra** [comment]
This is being tracked elsewhere.
